// export const LISTINGS_SAGA = "LISTINGS_SAGA";
export const LISTINGS_API_REQUEST = "LISTINGS_API_REQUEST";
export const LISTINGS_API_START = "LISTINGS_API_START";
export const LISTINGS_API_RESULT = "LISTINGS_API_RESULT";

export const MAP_LOADED = "MAP_LOADED";
export const SET_BROWSER_LOCATION = "SET_BROWSER_LOCATION";
export const SHOW_INFOWINDOW = "SHOW_INFOWINDOW";
export const SHOW_SIDEDRAWER = "SHOW_SIDEDRAWER";

export const UPDATE_FETCHED_LISTINGS = "UPDATE_FETCHED_LISTINGS";
export const UPDATE_LISTINGS_ASPECT = "UPDATE_LISTINGS_ASPECT";
export const UPDATE_LISTINGS_REDUCER = "UPDATE_LISTINGS_REDUCER";

export const CATEGORIES_API_REQUEST = "CATEGORIES_API_REQUEST";
export const CATEGORIES_API_START = "CATEGORIES_API_START";
export const CATEGORIES_API_RESULT = "CATEGORIES_API_RESULT";
export const UPDATE_CATEGORIES_ASPECT = "UPDATE_CATEGORIES_ASPECT";
export const UPDATE_SELECTED_CATEGORIES = "UPDATE_SELECTED_CATEGORIES";

export const UPDATE_SESSION_ASPECT = "UPDATE_SESSION_ASPECT";
export const UPDATE_SESSION_REDUCER = "UPDATE_SESSION_REDUCER";
